-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.book
(
    isbn character varying(10) COLLATE pg_catalog."default" NOT NULL,
    title character varying(500) COLLATE pg_catalog."default",
    author character varying(500) COLLATE pg_catalog."default",
    year character varying(10) COLLATE pg_catalog."default",
    publisher character varying(300) COLLATE pg_catalog."default",
    CONSTRAINT book_pkey PRIMARY KEY (isbn)
);

CREATE TABLE IF NOT EXISTS public.rating
(
    uid character varying(45) COLLATE pg_catalog."default" NOT NULL,
    isbn character varying(10) COLLATE pg_catalog."default" NOT NULL,
    rating character varying(5) COLLATE pg_catalog."default",
    CONSTRAINT rating_pkey PRIMARY KEY (uid, isbn)
);

CREATE TABLE IF NOT EXISTS public.user_data
(
    userid character varying(45) COLLATE pg_catalog."default" NOT NULL,
    country character varying(50) COLLATE pg_catalog."default",
    province character varying(50) COLLATE pg_catalog."default",
    age character varying(5) COLLATE pg_catalog."default",
    CONSTRAINT user_data_pkey PRIMARY KEY (userid)
);

ALTER TABLE IF EXISTS public.rating
    ADD CONSTRAINT foreign_isbn FOREIGN KEY (isbn)
    REFERENCES public.book (isbn) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.rating
    ADD CONSTRAINT foreign_uid FOREIGN KEY (uid)
    REFERENCES public.user_data (userid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;


-- remove user in user_data table but not in rating table
-- Step 1: Identify Users Not in Rating Table
CREATE TEMPORARY TABLE temp_users_to_keep AS
SELECT DISTINCT u.userid
FROM user_data u
LEFT JOIN rating r ON u.userid = r.uid
WHERE r.uid IS NOT NULL;

-- Step 2: Delete Users from user_data Table
DELETE FROM user_data
WHERE userid NOT IN (SELECT userid FROM temp_users_to_keep);

-- Clean up: Drop the temporary table
DROP TABLE temp_users_to_keep;